setup:
    meson setup build --cross-file cross/teensy-40.ini

build:
    meson compile -C build

flash:
    teensy-loader-cli --mcu=TEENSY40 -w build/firmware.hex

clean:
    meson subprojects purge --confirm
    rm -rf build
